language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - sudo apt-get install -yqq npm
  - sudo npm install -g bower && ln -s /usr/bin/nodejs /usr/bin/node
  - bower install 
before_script:
  - python pixelwalker/manage.py migrate 
script:
  - coverage run pixelwalker/manage.py test
after_script:
  - coveralls