language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - python pixelwalker/manage.py migrate 
script:
  - coverage run pixelwalker/manage.py test
after_script:
  - coveralls