version: '3'

services:
  db:
    image: postgres:latest
    hostname: db
    restart: always
    ports:
      - "5432:5432"

  rabbit:
    image: rabbitmq:latest
    hostname: rabbit
    restart: always
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  engine:
    build:
      context: ./Engine
      dockerfile: Dockerfile
    hostname: engine
    restart: always
    volumes:
      - .:/media_library
    ports:
      - "8000:8000"
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - db

  worker:
    build:
      context: ./Worker
      dockerfile: Dockerfile
    hostname: worker
    restart: always
    volumes:
      - .:/media_library
    links:
      - rabbit
      - redis
    depends_on:
      - engine