version: '3'

services:
  db:
    image: postgres
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    hostname: redis

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  engine:
    build:
      context: ./Engine
      dockerfile: Dockerfile
    hostname: engine
    command: ./run.sh
    volumes:
      - .:/media_library
    ports:
      - "8000:8000"
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - db

  worker:
    build:
      context: ./Worker
      dockerfile: Dockerfile
    hostname: engine
    command: ./run.sh
    volumes:
      - .:/media_library
    links:
      - rabbit
      - redis
    depends_on:
      - engine